package org.prototype.demo.user;

import java.sql.Connection;

import org.prototype.web.Business;
import org.prototype.business.ServiceDefine;
import org.prototype.sql.PreparedSql;

@ServiceDefine(open=false,value="create table")
public class CreateTable extends Business{
	
	void business(Connection connection){
		createTable(connection);
	}

	//@PreparedSql("create table common_user (id integer generated by default as identity (start with 1), name varchar(20) not null, primary key (id))")
	private void createTable(Connection connection) {
		// do nothing
	}

}
